spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  cloud:
    aws:
      s3:
        enabled: false

cloud-storage:
  host: ${CLOUD_STORAGE_HOST}
  port: ${CLOUD_STORAGE_PORT}
  bucket: ${CLOUD_STORAGE_BUCKET_NAME}
  region: ${CLOUD_STORAGE_REGION}
  access-key: ${CLOUD_STORAGE_ACCESS_KEY}
  secret-key: ${CLOUD_STORAGE_SECRET_KEY}
  preview-directory: temp
  persistence-directory: saved