spring:
  application:
    name: isek-ai
  profiles.default: dev
  config:
    import:
      - classpath:config/application-security.yml
      - classpath:config/application-gemini.yml
      - classpath:config/application-prompt.yml
      - classpath:config/application-rtzr.yml
  threads:
    virtual:
      enabled: true

ai-server:
  web-socket-url: ${AI_SERVER_WEBSOCKET_URL}

server:
  forward-headers-strategy: native
  port: 18081